### ISSUE TITLE
BC break in 1.4 because of extension class renaming

### ISSUE THREAD

**Issue by HeahDude** [petitpress/gps-messenger-bundle#19]
#18 broke BC by renaming the extension `GpsMessengerExtension` to `PetitPressGpsMessengerExtension`.

This should be either documented as such, or better, reverted, maybe reintroduced in 2.x after proper deprecation.

**Comment by pulzarraider** [comment]
That class is marked as final and should not be used outside of this bundle. Can you please give us more information about the issue? Why do you think it is BC break? Do you see some errors?

The change was needed as the PR adds new configuration option and I wanted to make this bundle more compatible with  [Symfony bundle best practices](https://symfony.com/doc/current/bundles/best_practices.html#bundle-name) without renaming the main bundle class.

**Comment by pulzarraider** [comment]
@HeahDude Thank you for your MR. This bundle has already version 2 available. I think we can close this issue.
