### ISSUE TITLE
Tag 0.1.3

### ISSUE THREAD

**Issue by mickprev** [petitpress/gps-messenger-bundle#2]
Hello @marforon,

When do you plan to tag the next release (0.1.3)? I will need the latest push development on master :)

**Comment by marforon** [comment]
Hi @mickprev ,

working on it, sorry for delay. I set up CI and I will tag it as 1.0.0, because there are some bc breaks and also it's time to step up with this bundle.

**Comment by mickprev** [comment]
Great! Thanks!
