### ISSUE TITLE
Symfony 7 compatibility

### ISSUE THREAD

**Issue by remi-vasco** [petitpress/gps-messenger-bundle#27]
Hello,

I was wondering if this bundle is compatible with Symfony 7 ?

I get composer failed dependencies error when trying to install

Thanks

**Comment by marforon** [comment]
Hi, not yet, we plan to add support in the first quarter of 2024. In the meantime, anyone is welcome to create a PR.

**Comment by remi-vasco** [comment]
Hi, thanks for you quick response.
If I am migrating my app earlier, I will try to make the PR.

Thanks

**Comment by marforon** [comment]
done in 2.0.0 https://github.com/petitpress/gps-messenger-bundle/releases/tag/2.0.0
