### ISSUE TITLE
Deprecation in PetitPressGpsMessengerExtension

### ISSUE THREAD

**Issue by dannyvw** [petitpress/gps-messenger-bundle#34]
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "PetitPress\GpsMessengerBundle\DependencyInjection\PetitPressGpsMessengerExtension".

**Comment by pulzarraider** [comment]
Fixed in 3.0.1. Thank you @dannyvw for reporting the issue.
