### ISSUE TITLE
Are Retry and Delay strategies possible ?

### ISSUE THREAD

**Issue by pdoreau** [petitpress/gps-messenger-bundle#8]
Retry in case of failure, and Delay to wait before putting a message to a queue, are possible strategies with [Swarrot / Rabbitmq](https://github.com/swarrot/SwarrotBundle).
I'm considering a Messenger / PubSub migration.

Are those features also available ?
Is there something particular or a difference to take into consideration ?

**Comment by pulzarraider** [comment]
PubSub subscription has retry policy built-in. See https://cloud.google.com/pubsub/docs/subscription-properties#retry_policies
